# Generated by Django 6.0.3 on 2026-04-10 10:01

import pgvector.django.vector
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', models.CharField(help_text='NFCタグの固有ID', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('time_phase', models.CharField(help_text='morning, afternoon, nightなど', max_length=50)),
                ('text', models.TextField(help_text='思考や出来事')),
                ('emotion_tag', models.CharField(blank=True, help_text='任意の手動タグ', max_length=50, null=True)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True)),
            ],
        ),
    ]
