# Generated by Django 6.0.3 on 2026-04-10 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='embedding',
        ),
    ]
