# Generated by Django 6.0.3 on 2026-04-17 03:40

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_remove_event_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
    ]
