# Generated by Django 6.0.3 on 2026-05-22 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_event_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', models.CharField(help_text='NFCに書き込まれる一意のID', max_length=100, unique=True)),
                ('name', models.CharField(help_text='表示名 (例: 赤石研デスク, 吉祥寺のカフェ)', max_length=100)),
                ('category', models.CharField(choices=[('work', '💻 ワーク（研究・作業）'), ('relax', '☕ リラックス（カフェ・自宅）'), ('transit', '🚃 移動・その他')], default='work', max_length=20)),
                ('description', models.TextField(blank=True, help_text='この場所のコンテキストやメモ', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
