# Generated by Django 6.0.3 on 2026-05-22 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(blank=True, help_text='表示名 (例: 赤石研デスク, 吉祥寺のカフェ)', max_length=100),
        ),
    ]
