"""
Django settings for TouchMind project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 【やっておくべきこと！！！】
# ① .envファイルを作成（作成場所：TouchMind/.env）
# ② NGROK_URL=（ここに自分の https://~ を格納）
load_dotenv(os.path.join(Path(__file__).resolve().parent.parent.parent, '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# 【やっておくべきこと！！！】
# ① .envファイルを作成（作成場所：TouchMind/.env）
# ② NGROK_URL=（ここに自分の https://~ を格納）
django_secret_key = os.getenv('DJANGO_SECRET_KEY')
SECRET_KEY = django_secret_key

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'TouchMind.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'TouchMind.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# PostgreSQL + pgvectorの想定（※ローカル開発時はSQLiteでも一旦動かせますが、ベクトル保存はPostgres推奨）
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'touchmind_db',
        'USER': 'user',
        'PASSWORD': 'password',
        'HOST': '127.0.0.1',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# ログイン画面のURL（@login_requiredで弾かれた時の飛ばし先）
LOGIN_URL = '/accounts/login/'

# （必要に応じて）ログアウト後のURL
LOGOUT_REDIRECT_URL = '/accounts/login/'

# ログイン成功時のリダイレクト先（今回は使わないが設定しておく）
LOGIN_REDIRECT_URL = '/'

# Cookieの有効期限を延ばす（デフォルトはブラウザを閉じるまで）
# スマホのブラウザを閉じても、半年間（約180日）はログイン状態をキープさせる
SESSION_COOKIE_AGE = ((60 * 60) * 24) * 7 # 7日間に設定（秒単位）

# ngrokからのPOSTリクエストを許可する
CSRF_TRUSTED_ORIGINS = []

ngrok_url = os.getenv('NGROK_URL')
if ngrok_url:
    CSRF_TRUSTED_ORIGINS.append(ngrok_url)